Add transforms for log-simplex
mjhajharia/transforms pull request #71
Opened 2023-09-19 22:15 UTC by sethaxen

Following #65, this PR adds versions of our transforms for the log-simplex. It also adds a log-Dirichlet target.

Note that `LogDirichlet(log_x | alpha) = Dirichlet(exp(log_x) | α) * exp(sum(log_x[1:(N-1)]))`, while the Jacobian corrections in the transforms are adjusted by `exp(-sum(log_x[1:(N-1)]))`, i.e. in the opposite direction.

2023-09-19 22:16 UTC, sethaxen commented
For some reason I haven't had any luck getting Stickbreaking with the log-simplex to be numerically stable.

2023-09-20 10:37 UTC, sethaxen commented
> For some reason I haven't had any luck getting Stickbreaking with the log-simplex to be numerically stable.

Turns out this was because the Jacobian determinant in the paper was off by an index. With the correct determinant, it works fine.

2023-09-25 19:47 UTC, spinkney requested changes
Looks good! The loop changes are optional. The only change is to remove the `negative_infinity()` in the `NormalizedExponential` transform.

2023-09-25 19:47 UTC, spinkney commented on target_densities/LogDirichlet.stan
> +      lp += alpha[i] * log_theta[i];
I'm fine with the loops but if we want to remove them we can do a `dot_product(alpha, log_theta)` here.

2023-09-25 19:47 UTC, spinkney commented on transforms/log_simplex/ALR.stan
> +      log_x[i] = y[i] - log_r;
We can do
```stan
   real log_r = log1p_exp(log_sum_exp(y));
   vector[N] log_x = append_row(y - log_r, -log_r);
```

2023-09-25 19:47 UTC, spinkney commented on transforms/log_simplex/NormalizedExponential.stan
> +    real log_r = negative_infinity();
I don't think we need to initialize this to `negative_infinity()`

2023-09-25 19:47 UTC, spinkney commented on transforms/log_simplex/NormalizedExponential.stan
> +      target += -log_x[i];
this can be 
```stan
target += -log_x[1:N - 1];
```

2023-09-25 19:47 UTC, spinkney commented on transforms/log_simplex/StanStickbreaking.stan
> +    target += -log_x[i];
Similarly, we can make this
```stan
target += -log_x[1:N - 1];
```

2023-09-25 19:47 UTC, spinkney commented on transforms/log_simplex/Stickbreaking.stan
> +    }
We can get rid of this loop but it's probably not worth it.

2023-09-25 20:05 UTC, sethaxen commented on transforms/log_simplex/ALR.stan
> +      log_x[i] = y[i] - log_r;
I'm not certain what Stan actually compiles to, but I'm wondering if `append_row(y - log_r, -log_r)` first allocates `y - log_r` and then allocates a copy with `-log_r` appended to it, while this version only allocates once. If not, your suggestion is certainly cleaner and probably preferable.

2023-09-25 20:06 UTC, sethaxen commented on transforms/log_simplex/NormalizedExponential.stan
> +      target += -log_x[i];
Incrementing a scalar by a slice of an array implicitly sums the slice and then increments? Is this documented behavior?

2023-09-25 20:24 UTC, spinkney commented on transforms/log_simplex/NormalizedExponential.stan
> +      target += -log_x[i];
https://mc-stan.org/docs/reference-manual/increment-log-prob.html#vectorization

2023-09-26 08:45 UTC, sethaxen commented on transforms/log_simplex/ALR.stan
> +      log_x[i] = y[i] - log_r;
I changed it to use multi-index assignment: https://mc-stan.org/docs/reference-manual/language-multi-indexing.html#multiple-index-semantics

2023-09-26 08:54 UTC, sethaxen commented
This PR also incorporates the changes in #72 and #73 but for the log-simplex.

2023-09-26 14:08 UTC, bob-carpenter commented
The reference doc is here:  https://mc-stan.org/docs/stan-users-guide/multi-indexing.html

Yes, it allocates an intermediate and copies.  We're working on making it lazy with expression templates.

2023-09-26 18:09 UTC, spinkney commented
LGTM!

2023-09-26 18:09 UTC, merged